"""
Build poster v8 (A0 portrait) with all the new Phase 5 figures slotted into a
clean 6-section structure.

Story arc:
  1. Question + system    (intro)
  2. Activin reveals latent multipolar potential
  3. Mezzo+ patterns the AP axis
  4. Pole emergence is sequential, not simultaneous
  5. Cortical mechanics signature - co-localised with fate
  6. Pole geometry differs between ctrl and Activin
  Conclusions banners + References + Acknowledgements footer

Output:
  Z:\Megha_Kattimani\Full_pipeline test\Lyn_mezzo_phase5_morphometrics\poster\poster_kattimani_v8.pptx

Notes:
  - All figure paths point to files generated by the Phase 5 scripts.
  - EMBL-green visual language, Gareth-style claim-as-header section titles.
  - Each section is a tcolorbox-style block (white body, navy header bar).
  - QR / EMBL logo / poster# slots are placeholders for manual insertion.
"""
from pathlib import Path
from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR

KYM = Path(r"Z:\Megha_Kattimani\Full_pipeline test\Lyn_mezzo_phase5_kymograph\plots")
MORPH = Path(r"Z:\Megha_Kattimani\Full_pipeline test\Lyn_mezzo_phase5_morphometrics\plots")
P3 = Path(r"Z:\Megha_Kattimani\Full_pipeline test\Lyn_mezzo_phase3\plots")
OUT_DIR = Path(r"Z:\Megha_Kattimani\Full_pipeline test\Lyn_mezzo_phase5_morphometrics\poster")
OUT_DIR.mkdir(parents=True, exist_ok=True)
OUT_FILE = OUT_DIR / "poster_kattimani_v8.pptx"

# A0 portrait dimensions (841 mm x 1189 mm = 33.11" x 46.81")
A0_W_IN = 33.11
A0_H_IN = 46.81

# Visual palette (EMBL-aligned)
EMBL_GREEN = RGBColor(0x00, 0xA6, 0x89)
EMBL_NAVY = RGBColor(0x21, 0x29, 0x5C)
EMBL_RED = RGBColor(0xC0, 0x48, 0x48)
EMBL_MOSS = RGBColor(0x97, 0xBC, 0x62)
BG_CREAM = RGBColor(0xF7, 0xF2, 0xE7)
TEXT_DARK = RGBColor(0x1F, 0x1F, 0x1F)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)
GREY = RGBColor(0x99, 0x99, 0x99)
LIGHT_GREY = RGBColor(0xE5, 0xE0, 0xD3)


def add_rect(slide, x_in, y_in, w_in, h_in, fill, line=None):
    shp = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE,
                                  Inches(x_in), Inches(y_in),
                                  Inches(w_in), Inches(h_in))
    shp.fill.solid()
    shp.fill.fore_color.rgb = fill
    if line is None:
        shp.line.fill.background()
    else:
        shp.line.color.rgb = line
        shp.line.width = Pt(0.75)
    return shp


def add_textbox(slide, x_in, y_in, w_in, h_in, text, *,
                size=18, bold=False, color=TEXT_DARK,
                align=PP_ALIGN.LEFT, anchor=MSO_ANCHOR.TOP,
                font="Arial"):
    tb = slide.shapes.add_textbox(Inches(x_in), Inches(y_in),
                                   Inches(w_in), Inches(h_in))
    tf = tb.text_frame
    tf.word_wrap = True
    tf.margin_left = Pt(2); tf.margin_right = Pt(2)
    tf.margin_top = Pt(2); tf.margin_bottom = Pt(2)
    tf.vertical_anchor = anchor
    lines = text.split("\n") if isinstance(text, str) else text
    for i, line in enumerate(lines):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        p.alignment = align
        run = p.add_run()
        run.text = line
        run.font.size = Pt(size); run.font.bold = bold
        run.font.color.rgb = color; run.font.name = font
    return tb


def add_section_header(slide, x_in, y_in, w_in, num, title, h_in=1.0):
    """Coloured pill header for a numbered section."""
    add_rect(slide, x_in, y_in, w_in, h_in, EMBL_NAVY)
    # number circle
    add_rect(slide, x_in + 0.1, y_in + 0.1, 0.8, h_in - 0.2, EMBL_GREEN)
    add_textbox(slide, x_in + 0.1, y_in + 0.1, 0.8, h_in - 0.2,
                str(num), size=42, bold=True, color=WHITE,
                align=PP_ALIGN.CENTER, anchor=MSO_ANCHOR.MIDDLE)
    add_textbox(slide, x_in + 1.0, y_in, w_in - 1.1, h_in, title,
                size=30, bold=True, color=WHITE, align=PP_ALIGN.LEFT,
                anchor=MSO_ANCHOR.MIDDLE)


def add_block(slide, x_in, y_in, w_in, h_in):
    """White content block with subtle border."""
    add_rect(slide, x_in, y_in, w_in, h_in, WHITE, line=LIGHT_GREY)


def add_image(slide, path, x_in, y_in, w_in, h_in):
    """Add image fitted to bounding box, centred."""
    if not Path(path).exists():
        add_rect(slide, x_in, y_in, w_in, h_in, LIGHT_GREY)
        add_textbox(slide, x_in, y_in, w_in, h_in,
                    f"[missing: {Path(path).name}]",
                    size=18, color=GREY, align=PP_ALIGN.CENTER,
                    anchor=MSO_ANCHOR.MIDDLE)
        return
    slide.shapes.add_picture(str(path), Inches(x_in), Inches(y_in),
                               width=Inches(w_in), height=Inches(h_in))


# ---------------------------------------------------------------------------
def build():
    prs = Presentation()
    prs.slide_width = Inches(A0_W_IN)
    prs.slide_height = Inches(A0_H_IN)
    slide = prs.slides.add_slide(prs.slide_layouts[6])  # blank

    # Page background
    add_rect(slide, 0, 0, A0_W_IN, A0_H_IN, BG_CREAM)

    # ---- HEADER STRIP -----------------------------------------------------
    add_rect(slide, 0, 0, A0_W_IN, 3.2, EMBL_NAVY)

    # EMBL logo placeholder (top-left)
    add_rect(slide, 0.6, 0.5, 3.0, 2.2, EMBL_GREEN)
    add_textbox(slide, 0.6, 0.5, 3.0, 2.2, "EMBL LOGO\n(replace in PPT)",
                size=18, bold=True, color=WHITE, align=PP_ALIGN.CENTER,
                anchor=MSO_ANCHOR.MIDDLE)

    # QR code placeholder (top-right)
    add_rect(slide, A0_W_IN - 3.6, 0.5, 3.0, 2.2, EMBL_GREEN)
    add_textbox(slide, A0_W_IN - 3.6, 0.5, 3.0, 2.2,
                "QR\nScan to follow the work",
                size=16, bold=True, color=WHITE, align=PP_ALIGN.CENTER,
                anchor=MSO_ANCHOR.MIDDLE)

    # Tagline + official title + author (centre)
    add_textbox(slide, 4.0, 0.4, A0_W_IN - 8.0, 1.2,
                "How does a self-organising tissue choose one organiser, or many?",
                size=44, bold=True, color=WHITE, align=PP_ALIGN.CENTER,
                anchor=MSO_ANCHOR.MIDDLE)
    add_textbox(slide, 4.0, 1.65, A0_W_IN - 8.0, 0.85,
                "Chemical perturbation of morphogen pathways affects "
                "self-organising gastrulation dynamics ex vivo",
                size=24, bold=False, color=WHITE, align=PP_ALIGN.CENTER,
                anchor=MSO_ANCHOR.MIDDLE)
    add_textbox(slide, 4.0, 2.55, A0_W_IN - 8.0, 0.6,
                "Megha Kattimani  |  Trivedi Lab, EMBL Barcelona  |  "
                "megha.kattimani@embl.es  |  Poster #XX",
                size=18, bold=False, color=WHITE, align=PP_ALIGN.CENTER,
                anchor=MSO_ANCHOR.MIDDLE)

    # ---- SECTION 1: question + system ------------------------------------
    y = 3.6
    add_section_header(slide, 0.4, y, A0_W_IN - 0.8, 1,
                        "Introduction: what sets the number of organisers?")
    y += 1.05
    add_block(slide, 0.4, y, A0_W_IN - 0.8, 5.0)
    # Left column = text
    add_textbox(slide, 0.7, y + 0.15, 14.0, 4.7,
                "Vertebrate gastrulation requires a single organiser. "
                "Pescoids (zebrafish blastula cap explants) self-organise "
                "into mesendoderm poles ex vivo, with no maternal axis.\n\n"
                "Questions:\n"
                "  1. How robust is organiser formation against chemical "
                "perturbation, and what sets organiser number?\n"
                "  2. Are multi-pole outcomes driven by chemistry or by "
                "tissue mechanics?\n"
                "  3. Does cortical mechanics precede or follow fate "
                "commitment at organiser sites?\n\n"
                "Parallels cortical-mechanics + cell-flow framework recently "
                "shown to underlie embryonic regulation in mouse / chick "
                "(Caldarelli 2024) - tested here with chemical access in "
                "zebrafish ex vivo.",
                size=18, color=TEXT_DARK)
    # Right column = methods schematic
    add_image(slide, KYM / "00_methods_and_framing.png",
              14.8, y + 0.15, A0_W_IN - 15.2, 4.7)

    # ---- SECTION 2: phenotype distribution -------------------------------
    y += 5.1
    add_section_header(slide, 0.4, y, A0_W_IN - 0.8, 1,
                        "Activin 3-5 hpf reveals a latent multipolar potential")
    y += 1.05
    add_block(slide, 0.4, y, A0_W_IN - 0.8, 6.5)
    # Lead with the punch numbers
    add_textbox(slide, 0.7, y + 0.15, 14.0, 6.2,
                "From 0% multipolar in P_ctrl (n=15) to ~32% in P_Activin "
                "3-5 hpf (n=37).\n\n"
                "Identical chemistry inputs lead to discrete phenotypes:\n"
                "  - monopolar (single organiser)\n"
                "  - bipolar (mezzo or coord)\n"
                "  - multipolar (>=3 organisers)\n"
                "  - disorganised multipolar\n\n"
                "Mean mezzo+ pole count rises from 0 (ctrl) to >2 (Activin).\n"
                "Maximum poles per pescoid: 0 (ctrl) -> 7 (Activin).\n\n"
                "Implication: chemistry alone underdetermines outcome - "
                "the system selects between discrete states.",
                size=18, color=TEXT_DARK)
    add_image(slide, MORPH / "01_primary_pole_ar.png",
              14.8, y + 0.15, A0_W_IN - 15.2, 6.2)

    # ---- SECTION 3: AP-mezzo kymograph + population profile --------------
    y += 6.6
    add_section_header(slide, 0.4, y, A0_W_IN - 0.8, 1,
                        "Mezzo+ pattern resolves into discrete domains along AP axis")
    y += 1.05
    add_block(slide, 0.4, y, A0_W_IN - 0.8, 7.5)
    # Big paired kymograph spans full width
    add_image(slide, KYM / "20_paired_perimeter_apmezzo.png",
              0.7, y + 0.15, A0_W_IN - 1.4, 5.5)
    add_textbox(slide, 0.7, y + 5.75, A0_W_IN - 1.4, 1.55,
                "Paired kymographs (top = perimeter mechanics, "
                "bottom = AP-mezzo fate signal). For each pescoid: boundary "
                "bulges (red top) co-localise with mezzo+ poles (bright "
                "bottom). Monopolar -> 1 peak; bipolar -> 2 peaks at "
                "opposite ends; multipolar -> several. Population profile "
                "by phenotype (see Section 4) confirms a clean peak at AP=1 "
                "for monopolar (n=13) once orientation is normalised.",
                size=16, color=TEXT_DARK)

    # ---- SECTION 4: pole emergence is sequential -------------------------
    y += 7.6
    add_section_header(slide, 0.4, y, A0_W_IN - 0.8, 1,
                        "Pole emergence is sequential, not parallel - asymmetric in size and time")
    y += 1.05
    add_block(slide, 0.4, y, A0_W_IN - 0.8, 7.5)
    # Left = pole area vs time, Right = paired emergence
    add_image(slide, KYM / "10_v2_pole_area_vs_time.png",
              0.7, y + 0.2, (A0_W_IN - 1.7) / 2, 7.1)
    add_image(slide, KYM / "11_v2_pole_emergence_clean.png",
              0.7 + (A0_W_IN - 1.4) / 2, y + 0.2, (A0_W_IN - 1.7) / 2, 7.1)

    # ---- SECTION 5: cortical mechanics signature -------------------------
    y += 7.6
    add_section_header(slide, 0.4, y, A0_W_IN - 0.8, 1,
                        "Cortical mechanics signature - and it predicts where poles will form")
    y += 1.05
    add_block(slide, 0.4, y, A0_W_IN - 0.8, 6.7)
    # Three-panel summary
    add_image(slide, MORPH / "13_mechanics_combined_for_poster.png",
              0.7, y + 0.15, A0_W_IN - 1.4, 4.2)
    # Caldarelli callout
    add_rect(slide, 0.7, y + 4.5, A0_W_IN - 1.4, 2.0, BG_CREAM, line=EMBL_RED)
    add_textbox(slide, 0.9, y + 4.6, A0_W_IN - 1.8, 1.8,
                "Mechanics is a CAUSE, not just a consequence.  "
                "Before the pole emerges, the future site already shows "
                "elevated cortical coherence vs random sites in the same "
                "pescoid (65% above 0, Wilcoxon p = 0.031).  AT peak, "
                "coherence inside the pole is suppressed in 18 / 25 pescoids "
                "(Wilcoxon p = 0.0025).\n\n"
                "Parallels the cortical-actomyosin + cell-flow framework "
                "shown to underlie embryonic regulation in chick / quail "
                "embryos including ectopic-organiser formation "
                "(Caldarelli et al. Nature 2024) - same logic, vertebrate "
                "ex-vivo readout.",
                size=16, bold=False, color=TEXT_DARK)

    # ---- SECTION 6: pole morphometrics -----------------------------------
    y += 6.8
    add_section_header(slide, 0.4, y, A0_W_IN - 0.8, 1,
                        "Activin poles are 2x more elongated and occupy 2x more of the pescoid")
    y += 1.05
    add_block(slide, 0.4, y, A0_W_IN - 0.8, 6.5)
    add_image(slide, MORPH / "02_pole_relative_size.png",
              0.7, y + 0.15, (A0_W_IN - 1.7) / 2, 6.0)
    add_image(slide, MORPH / "04_pescoid_vs_pole_elongation.png",
              0.7 + (A0_W_IN - 1.4) / 2, y + 0.15, (A0_W_IN - 1.7) / 2, 6.0)

    # ---- CONCLUSION BANNERS ----------------------------------------------
    y += 6.6
    band_w = (A0_W_IN - 1.6) / 3
    for i, (color, num, head, body) in enumerate([
        (EMBL_GREEN, "1", "Multistable, not graded",
         "Activin lifts multipolarity from 0% to ~32%. Identical chemistry, "
         "discrete phenotypes."),
        (EMBL_RED, "2", "Sequential competitive nucleation",
         "Secondary poles are <50% of primary and emerge 1-3 hpf later. "
         "Rules out parallel symmetry breaking."),
        (EMBL_NAVY, "3", "Mechanics predicts fate",
         "Pre-emergence cortical alignment elevated at future pole sites "
         "(65% Wilcoxon p=0.03). Caldarelli framework, ex vivo."),
    ]):
        x = 0.4 + i * (band_w + 0.2)
        add_rect(slide, x, y, band_w, 3.0, WHITE, line=color)
        add_rect(slide, x, y, band_w, 0.7, color)
        add_textbox(slide, x + 0.1, y, band_w - 0.2, 0.7,
                    f"  Conclusion {num}: {head}",
                    size=22, bold=True, color=WHITE, anchor=MSO_ANCHOR.MIDDLE)
        add_textbox(slide, x + 0.2, y + 0.85, band_w - 0.4, 2.0, body,
                    size=18, color=TEXT_DARK)

    # ---- FOOTER: refs + acknowledgements ---------------------------------
    y += 3.2
    add_rect(slide, 0.4, y, A0_W_IN - 0.8, A0_H_IN - y - 0.4, EMBL_NAVY)
    add_textbox(slide, 0.7, y + 0.1, (A0_W_IN - 1.4) / 2, A0_H_IN - y - 0.6,
                "References\n"
                "[1] Caldarelli, Chamolly, Villedieu et al. (Nature 2024). "
                "Self-organized tissue mechanics underlie embryonic regulation.\n"
                "    Fig 1 motivates the inside-vs-outside cortical-coherence "
                "analysis here.\n"
                "[2] Claussen, Brauns & Streichan (2025). Searching for physical "
                "principles of morphogenesis.\n"
                "[3] Weng, Huebner & Wallingford. Convergent extension requires "
                "adhesion-dependent biomechanical integration.\n"
                "[4] Tozluoglu & Mao. On folding morphogenesis, a mechanical "
                "problem.",
                size=14, color=WHITE)
    add_textbox(slide, 0.7 + (A0_W_IN - 1.4) / 2 + 0.2, y + 0.1,
                (A0_W_IN - 1.4) / 2, A0_H_IN - y - 0.6,
                "Acknowledgements\n"
                "Vikas Trivedi (PI, EMBL Barcelona). Trivedi lab members "
                "for fish husbandry and discussions. EMBL Barcelona imaging "
                "core. IMPRS for prior training. Conference attendance "
                "supported by the Trivedi group.\n\n"
                "Contact: megha.kattimani@embl.es",
                size=14, color=WHITE)

    prs.save(str(OUT_FILE))
    print(f"Saved -> {OUT_FILE}")


if __name__ == "__main__":
    build()
