"""
Fine-tune the pescoid U-Net for the titration BF (260409 mezzo titration).

Problem: the pretrained U-Net (unet_pescoid_v2.pth) was trained on BF with a
mid-gray background. The titration BF has a near-saturated white background, so
the U-Net inverts (segments background instead of the dark pescoid). No
preprocessing (histogram-match, gamma, invert) fixes this reliably.

Fix: adapt the U-Net to the titration BF distribution by fine-tuning on
pseudo-labels generated by the classical Otsu-on-inverted-BF segmenter (which
works well on this data). This is self-training / distillation: the classical
segmenter is the teacher, the U-Net learns a smoother, shape-regularised
version that generalises across all 58 scenes.

Steps:
  1. Sample frames across all 5 dose groups.
  2. Generate Otsu pseudo-masks; quality-filter (plausible area, compact).
  3. Fine-tune UNet from unet_pescoid_v2.pth.
  4. Save unet_pescoid_titration.pth.
  5. Validate on held-out frames (overlay PNG).

Usage:
    python phase1_titration_finetune_unet.py
"""
import sys
from pathlib import Path
import numpy as np
import tifffile
import torch
import torch.optim as optim
from torch.utils.data import DataLoader
from scipy import ndimage as ndi
from skimage import morphology, measure, filters
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "benchmarking_segment_tools"))
from run_3dunet import UNet, PescoidDataset, DiceBCELoss
from phase1_titration_qc import (norm_pct, z_project_best_focus, z_project_max,
                                  segment_classical, UNET_PATH, CH_BF, CH_GFP,
                                  SCENE_GROUPS)

DATA_ROOT = Path(
    r"Z:\Megha_Kattimani\Imaging\Zeiss"
    r"\260409_mezzo_titration_3-5hpf_obj10x_8hpf\tiff"
)
OUT_MODEL = Path(r"C:\Users\kattimani\Project\pescoid-image-analysis"
                 r"\annotation_workspace\model\unet_pescoid_titration.pth")
VAL_PNG = Path(r"c:\Users\kattimani\Project\pescoid-image-analysis"
               r"\_titration_finetune_validation.png")

# Training-frame sampling
TRAIN_SCENES = {
    "E":       [6, 10],
    "Pctrl":   [15, 18],
    "P10ngml": [23, 52],
    "P30ngml": [30, 34],
    "P50ngml": [40, 45, 58],
}
TRAIN_FRAMES = [4, 10, 16, 22, 28]   # spread across the 32-frame movie
HELDOUT_SCENES = [("E", 7), ("Pctrl", 16), ("P30ngml", 33), ("P50ngml", 48)]

# Pseudo-label quality filter
MIN_AREA = 8000
MAX_AREA = 140000
MIN_SOLIDITY = 0.80

N_EPOCHS = 80
LEARNING_RATE = 5e-4   # lower than scratch (1e-3) since fine-tuning
BATCH_SIZE = 4


def scene_path(scene_num):
    for f in DATA_ROOT.glob("*.tif"):
        import re
        m = re.search(r"#(\d+)", f.stem)
        if m and int(m.group(1)) == scene_num:
            return f
    return None


def good_mask(mask):
    if mask.sum() < MIN_AREA or mask.sum() > MAX_AREA:
        return False
    props = measure.regionprops(mask.astype(int))
    if not props:
        return False
    p = max(props, key=lambda r: r.area)
    return p.solidity >= MIN_SOLIDITY


def body_plus_mezzo_label(bf, gfp_raw):
    """Pseudo-label = BF body (Otsu) UNION mezzo+ regions attached to it.
    Captures mezzo-bright tips / secondary poles that the BF-only Otsu misses."""
    body = segment_classical(bf, method="otsu")
    if not body.any():
        return body
    # bg-subtracted mezzo, threshold at bg + k*std (only clearly-bright signal)
    bg_pix = gfp_raw[~body] if (~body).any() else gfp_raw
    bg_mean, bg_std = float(bg_pix.mean()), float(bg_pix.std())
    gfp_bgsub = (gfp_raw - bg_mean)
    mezzo_pos = gfp_bgsub > (5.0 * bg_std)
    mezzo_pos = morphology.remove_small_objects(mezzo_pos, 60)
    # union, bridge necks, fill, keep the body-connected component
    combined = body | mezzo_pos
    combined = morphology.binary_closing(combined, morphology.disk(6))
    combined = ndi.binary_fill_holes(combined)
    lab, n = ndi.label(combined)
    if n > 0:
        # keep the component that overlaps the original body most
        best, best_ov = None, -1
        for k in range(1, n + 1):
            ov = (lab == k)[body].sum()
            if ov > best_ov:
                best_ov, best = ov, k
        combined = (lab == best)
    return combined.astype(bool)


def build_training_set():
    images, labels = [], []
    n_kept, n_rej = 0, 0
    for group, scenes in TRAIN_SCENES.items():
        for sc in scenes:
            p = scene_path(sc)
            if p is None:
                continue
            arr = tifffile.imread(str(p))
            T = arr.shape[0]
            for t in TRAIN_FRAMES:
                if t >= T:
                    continue
                bf = norm_pct(z_project_best_focus(arr[t, :, CH_BF]))
                gfp_raw = z_project_max(arr[t, :, CH_GFP])
                mask = body_plus_mezzo_label(bf, gfp_raw)
                if good_mask(mask):
                    images.append((bf * 255).astype(np.uint8))
                    labels.append(mask.astype(np.float32))
                    n_kept += 1
                else:
                    n_rej += 1
    print(f"  Pseudo-labels (BF + mezzo union): kept {n_kept}, rejected {n_rej}")
    return images, labels


def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    print("Building Otsu pseudo-label training set...")
    images, labels = build_training_set()
    if len(images) < 10:
        print("Too few training images; aborting.")
        return

    dataset = PescoidDataset(images, labels, augment=True)
    loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True, num_workers=0)

    model = UNet(in_channels=1, out_channels=1, features=[32, 64, 128, 256]).to(device)
    model.load_state_dict(torch.load(str(UNET_PATH), map_location=device, weights_only=True))
    print(f"Loaded pretrained weights from {UNET_PATH.name}")

    criterion = DiceBCELoss()
    optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE, weight_decay=1e-5)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=N_EPOCHS)

    model.train()
    for epoch in range(N_EPOCHS):
        epoch_loss = 0.0
        for imgs, lbls in loader:
            imgs, lbls = imgs.to(device), lbls.to(device)
            optimizer.zero_grad()
            preds = model(imgs)
            loss = criterion(preds, lbls)
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
        scheduler.step()
        if (epoch + 1) % 10 == 0 or epoch == 0:
            print(f"  epoch {epoch+1}/{N_EPOCHS}  loss={epoch_loss/len(loader):.4f}")

    OUT_MODEL.parent.mkdir(parents=True, exist_ok=True)
    torch.save(model.state_dict(), str(OUT_MODEL))
    print(f"Saved fine-tuned model -> {OUT_MODEL}")

    # ---- Validate on held-out scenes ----
    model.eval()
    fig, axes = plt.subplots(len(HELDOUT_SCENES), 3, figsize=(12, 4 * len(HELDOUT_SCENES)))
    for ri, (group, sc) in enumerate(HELDOUT_SCENES):
        p = scene_path(sc)
        arr = tifffile.imread(str(p))
        for ci, t in enumerate([8, 16, 24]):
            bf = norm_pct(z_project_best_focus(arr[t, :, CH_BF]))
            with torch.no_grad():
                pr = torch.sigmoid(model(torch.from_numpy(
                    bf.astype(np.float32)[None, None]).to(device))).cpu().numpy()[0, 0]
            m = pr > 0.5
            m = ndi.binary_fill_holes(m)
            m = morphology.binary_closing(m, morphology.disk(3))
            m = ndi.binary_fill_holes(m)
            lab, n = ndi.label(m)
            if n > 0:
                sz = ndi.sum(m, lab, range(1, n + 1))
                m = (lab == (np.argmax(sz) + 1))
            axes[ri, ci].imshow(bf, cmap="gray")
            for c in measure.find_contours(m.astype(float), 0.5):
                axes[ri, ci].plot(c[:, 1], c[:, 0], "r-", lw=1.3)
            axes[ri, ci].set_title(f"{group} #{sc} t={t} area={int(m.sum())}", fontsize=9)
            axes[ri, ci].axis("off")
    plt.suptitle("Fine-tuned U-Net validation on held-out titration scenes",
                 fontsize=13, fontweight="bold")
    plt.tight_layout(rect=[0, 0, 1, 0.97])
    plt.savefig(str(VAL_PNG), dpi=90, bbox_inches="tight")
    plt.close(fig)
    print(f"Validation overlay -> {VAL_PNG}")


if __name__ == "__main__":
    main()
